name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    if: github.repository_owner == 'CtrlCup'
    runs-on: ubuntu-latest
    concurrency:
      group: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install python-semantic-release
      - run: semantic-release version
      - run: semantic-release publish
